### ISSUE TITLE
Team roles incorrect

### ISSUE THREAD

**Issue by HughZurname** [HackSheffield/website#19]
https://www.hacksheffield.co/#team is displaying old roles like "Sponsorship officer", not looked at how this is specifically handled in the app, but probably needs fixing.

**Comment by dannycjones** [comment]
@HackSheffield/committee you should take the opportunity to add yourself to this file so that your profile on the website will be up to date and snazzy with social profiles (if you so desire) 

https://github.com/HackSheffield/people/blob/master/_data/people.yml

Just send in a pull request and it can be merged in!

**Comment by HughZurname** [comment]
Resolved with changes to HackSheffield/people#2
